export const SET_FLIGHTS = 'SET_FLIGHTS';
export const SHOW_ALL = 'SHOW_ALL';
export const FETCH_FLIGHTS_PENDING = 'FETCH_FLIGHTS_PENDING';
export const FETCH_FLIGHTS_FULFILLED = 'FETCH_FLIGHTS_FULFILLED';
export const FETCH_FLIGHTS_REJECTED = 'FETCH_FLIGHTS_REJECTED';